import React, { useState, useMemo, useRef, useEffect } from 'react';
import { Answer, LocalizedCategoryData, Language, SurveyDefinition, LocalizedScaleConfig, Profile, QuestionType, UIStrings } from './types';
import { SurveyService } from './services/SurveyService';
import { Results } from '@/components/Results/Results';
import { Header } from './components/Header';
import { Intro } from './components/Home/Intro';
import { Survey } from './components/Survey/Survey';
import { ProfileManager } from './components/Home/ProfileManager';
import { ImportManager } from './components/Home/ImportManager';
import { ShieldAlert } from 'lucide-react';
import { UI_TRANSLATIONS } from './translations';
import { AVAILABLE_SURVEYS } from './constants';
import { ProfileService } from './services/ProfileService';
// @ts-ignore - Assuming the package is available via importmap
import { decode } from '@toon-format/toon';
import { AdminDashboard } from './components/AdminDashboard';
import { LoginModal } from './components/Auth/LoginModal';
import { Recommendations } from './components/Recommendations/Recommendations';
import { DashboardResults } from './components/Results/DashboardResults';
import { PrivacyPolicy } from './components/Legal/PrivacyPolicy';
import { Routes, Route, useNavigate, useLocation, Navigate, useParams, useSearchParams } from 'react-router-dom';
import { FinishConfirmationModal } from './components/Survey/FinishConfirmationModal';
import { AboutPage } from './components/Info/AboutPage';
import { FaqPage } from './components/Info/FaqPage';
import { TermsPage } from './components/Info/TermsPage';
import { HowItWorksPage } from './components/Info/HowItWorksPage';
import { LandingPage } from './components/Info/LandingPage';
import { NewsPage } from './components/Info/NewsPage';
// @ts-ignore - Generated by vite-plugin-pwa
import { useRegisterSW } from 'virtual:pwa-register/react';

export enum AppState {
  INTRO = 'INTRO',
  SURVEY = 'SURVEY',
  RESULTS = 'RESULTS',
  RECOMMENDATIONS = 'RECOMMENDATIONS',
  DASHBOARD_RESULTS = 'DASHBOARD_RESULTS',
  USERS = 'USERS',
}

const LOCAL_STORAGE_KEY = 'neuroprofile_survey_state';

type Theme = 'light' | 'dark';

interface User {
  id: string | number;
  first_name: string;
  last_name?: string;
  username?: string;
  photo_url?: string;
  auth_date: number;
  hash: string;
}

/** Redirects to landing page if user is not authenticated. */
const ProtectedRoute: React.FC<{ user: User | null; children: React.ReactNode }> = ({ user, children }) => {
  const location = useLocation();
  if (!user) {
    const search = location.search;
    const redirectParam = `redirect=${encodeURIComponent(location.pathname)}`;
    const target = `/${search}${search ? (search.includes('?') ? '&' : '?') : '?'}${redirectParam}`;
    return <Navigate to={target} replace />;
  }
  return <>{children}</>;
};

const App: React.FC = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const [searchParams, setSearchParams] = useSearchParams();

  // PWA update logic
  const {
    offlineReady: [offlineReady, setOfflineReady],
    needRefresh: [needRefresh, setNeedRefresh],
    updateServiceWorker,
  } = useRegisterSW();

  const closePwaNotify = () => {
    setOfflineReady(false);
    setNeedRefresh(false);
  };

  // Unified Source Tracker for lead attribution (from ?s=f, ?s=t, etc.) and referrals (?ref=user_id)
  useEffect(() => {
    const s = searchParams.get('s');
    const ref = searchParams.get('ref');
    
    if (s || ref) {
      const newParams = new URLSearchParams(searchParams);
      
      if (s) {
        const sourceMap: Record<string, string> = {
          'f': 'facebook', 't': 'telegram', 'i': 'instagram', 'y': 'youtube',
          'l': 'linkedin', 'x': 'twitter', 'g': 'google', 'r': 'reddit',
        };
        const fullSource = sourceMap[s] || s;
        localStorage.setItem('lead_source', fullSource);
        newParams.delete('s');
      }
      
      if (ref) {
        localStorage.setItem('referred_by', ref);
        newParams.delete('ref');
      }
      
      // Clean URL after capturing to avoid scaring users
      setSearchParams(newParams, { replace: true });
    }
  }, [searchParams, setSearchParams]);

  const [appState, setAppState] = useState<AppState>(() => {
    const path = window.location.pathname;
    if (path === '/results') return AppState.DASHBOARD_RESULTS;
    if (path === '/users') return AppState.USERS;
    if (path.startsWith('/results/')) return AppState.RESULTS;
    if (path === '/dashboard') return AppState.DASHBOARD_RESULTS;
    if (path.startsWith('/survey/')) return AppState.SURVEY;
    return AppState.INTRO;
  });

  // Sync state with URL
  useEffect(() => {
    const path = location.pathname;
    if (path === '/') setAppState(AppState.INTRO);
    else if (path === '/results') setAppState(AppState.DASHBOARD_RESULTS);
    else if (path.startsWith('/results/')) setAppState(AppState.RESULTS);
    else if (path === '/recommendations') setAppState(AppState.RECOMMENDATIONS);
    else if (path === '/history' || path === '/dashboard') setAppState(AppState.DASHBOARD_RESULTS);
    else if (path === '/users') setAppState(AppState.USERS);
    else if (path === '/privacy') setAppState(AppState.INTRO); // Or a new state if needed, but INTRO/NONE is fine
    else if (path.startsWith('/survey/')) setAppState(AppState.SURVEY);
  }, [location.pathname]);

  const [currentCategoryIndex, setCurrentCategoryIndex] = useState(0);
  const [answers, setAnswers] = useState<Record<string, Answer>>({});
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof navigator === 'undefined') return 'en';
    const lang = navigator.language.toLowerCase();
    if (lang.includes('uk')) return 'uk';
    if (lang.includes('ru')) return 'ru';
    return 'en';
  });
  const [theme, setTheme] = useState<Theme>(() => {
    const saved = localStorage.getItem('neuroprofile_theme') as Theme;
    if (saved && (saved === 'light' || saved === 'dark')) return saved;
    if (globalThis.window !== undefined && globalThis.matchMedia?.('(prefers-color-scheme: dark)').matches) {
      return 'dark';
    }
    return 'light';
  });

  const [activeSurveyId, setActiveSurveyId] = useState<string>('full_aphantasia_profile'); // ID за замовчуванням
  const [currentSurvey, setCurrentSurvey] = useState<SurveyDefinition | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(false);

  const [profiles, setProfiles] = useState<Profile[]>(() => ProfileService.getProfiles());
  const [activeProfileId, setActiveProfileId] = useState<string | null>(() => {
    const loadedProfiles = ProfileService.getProfiles();
    const storedProfileId = localStorage.getItem('neuroprofile_active_profile_id');
    if (storedProfileId && loadedProfiles.some(p => p.id === storedProfileId)) {
      return storedProfileId;
    } else if (loadedProfiles.length > 0) {
      return loadedProfiles[0].id;
    }
    return null;
  });

  // Update HTML lang attribute
  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const [backendRecommendations, setBackendRecommendations] = useState<Record<string, string>>({});
  const [showLoginModal, setShowLoginModal] = useState<boolean>(false);
  const [loginModalConfig, setLoginModalConfig] = useState<{ title?: string, description?: string }>({});
  const [adminResults, setAdminResults] = useState<any[]>([]);
  const [showFinishConfirmation, setShowFinishConfirmation] = useState<boolean>(false);
  const [tone, setTone] = useState<string>(() => {
    const saved = localStorage.getItem('neuroprofile_tone');
    if (saved) return saved;
    return 'professional';
  });

  // Sync activeSurveyId from URL if in survey mode
  useEffect(() => {
    if (location.pathname.startsWith('/survey/')) {
      const idStr = location.pathname.split('/survey/')[1];
      if (idStr && idStr !== activeSurveyId) {
        setActiveSurveyId(idStr);
      }
    }
  }, [location.pathname, activeSurveyId]);
  const [user, setUser] = useState<User | null>(() => {
    const saved = localStorage.getItem('auth_token') || localStorage.getItem('telegram_auth');
    if (saved) {
      try {
        const data = JSON.parse(saved);
        const userData = data.user || data;
        if (userData && userData.id && userData.hash && !userData.error) {
          return userData;
        }
        console.warn('[App] Invalid auth in localStorage found and cleared');
        localStorage.removeItem('auth_token');
        localStorage.removeItem('telegram_auth');
        return null;
      } catch (e) {
        return null;
      }
    }
    return null;
  });

  // Auto-open login modal if redirected from a protected route
  useEffect(() => {
    const params = new URLSearchParams(location.search);
    if (params.get('redirect') && !user) {
      setShowLoginModal(true);
    }
  }, []);

  const isAdmin = useMemo(() => {
    if (!user) return false;
    const adminIds = (import.meta.env.VITE_ADMIN_USER_IDS || import.meta.env.VITE_ADMIN_TELEGRAM_IDS || '').split(',');
    return adminIds.some(id => String(id).trim() === String(user.id).trim());
  }, [user]);

  const [importingAnswers, setImportingAnswers] = useState<Record<string, Answer> | null>(null);
  const [hasExistingResults, setHasExistingResults] = useState<boolean>(false);

  const initialLoadRef = useRef(false);

  // Initialize
  useEffect(() => {
    let storedUserId = localStorage.getItem('neuroprofile_user_id');
    if (!storedUserId) {
      storedUserId = 'user_' + Math.random().toString(36).slice(2, 11) + '_' + Date.now().toString(36);
      localStorage.setItem('neuroprofile_user_id', storedUserId);
    }

    // Initial profiles state already set in constructor/useState

    // Login Listener
    const handleLogin = (e: any) => {
      const userData = e.detail;
      if (userData && userData.id && !userData.error) {
        console.log('[App] Login event received:', userData.first_name);
        setUser(userData);
        setShowLoginModal(false);

        // Redirect back to the page the user was trying to access
        const params = new URLSearchParams(window.location.search);
        const redirectTo = params.get('redirect');
        if (redirectTo && redirectTo.startsWith('/')) {
          navigate(redirectTo, { replace: true });
        }
      } else {
        console.warn('[App] Invalid login event ignored:', userData);
      }
    };
    globalThis.addEventListener('auth-login', handleLogin);
    globalThis.addEventListener('telegram-login', handleLogin); // Keep for compatibility if components use it

    return () => {
      globalThis.removeEventListener('auth-login', handleLogin);
      globalThis.removeEventListener('telegram-login', handleLogin);
    };
  }, []);

  // Sync profiles with User
  useEffect(() => {
    if (user) {
      // If logged in, we only care about the profile for this user
      const userProfileId = `g_${user.id}`;

      // Use latest profiles from service to avoid stale state issues
      const currentProfiles = ProfileService.getProfiles();
      let profile = currentProfiles.find(p => p.id === userProfileId);

      if (profile) {
        // Even if profile exists, ensure state is synced
        setProfiles(currentProfiles);
      } else {
        const name = `${user.first_name} ${user.last_name || ''}`.trim();
        ProfileService.createProfile(name, activeSurveyId, userProfileId);
        setProfiles(ProfileService.getProfiles());
      }

      if (activeProfileId !== userProfileId) {
        setActiveProfileId(userProfileId);
      }

      // Check if user already has results on backend
      if (!initialLoadRef.current) {
        initialLoadRef.current = true;
        ProfileService.loadResultFromBackend().then(result => {
          if (result && result.answers) {
            // result.answers is now keyed by test_type from backend migration
            setHasExistingResults(true);

            // Merge into local profiles
            setProfiles(prev => {
              const next = [...prev];
              const idx = next.findIndex(p => p.id === userProfileId);
              if (idx !== -1) {
                next[idx].answers = result.answers;
                next[idx].badges = result.badges;
                ProfileService.saveProfiles(next);
              }
              return next;
            });

            // Set current answers buffer
            if (activeSurveyId && result.answers[activeSurveyId]) {
              setAnswers(result.answers[activeSurveyId]);
            }

            if (result.gemini_recommendations) {
              setBackendRecommendations(
                typeof result.gemini_recommendations === 'string'
                  ? { [result.test_type || 'unknown']: result.gemini_recommendations }
                  : result.gemini_recommendations
              );
            }
          } else {
            setHasExistingResults(false);
          }
        }).catch(err => {
          console.error('[App] Failed to load results:', err);
          initialLoadRef.current = false;
        });
      }
    } else {
      setHasExistingResults(false);
      setBackendRecommendations({});
      initialLoadRef.current = false;
    }
  }, [user]); // Removed activeSurveyId from deps to avoid multiple loads when it changes

  // One-time cleanup: Deduplicate profiles by ID if they somehow got duplicated
  useEffect(() => {
    const currentProfiles = ProfileService.getProfiles();
    const uniqueProfilesMap = new Map();
    let hasDuplicates = false;

    currentProfiles.forEach(p => {
      if (uniqueProfilesMap.has(p.id)) {
        hasDuplicates = true;
      } else {
        uniqueProfilesMap.set(p.id, p);
      }
    });

    if (hasDuplicates) {
      const uniqueProfiles = Array.from(uniqueProfilesMap.values());
      ProfileService.saveProfiles(uniqueProfiles);
      setProfiles(uniqueProfiles);
    }
  }, []);

  // Fetch Survey Data (Simulation of DB call)
  useEffect(() => {
    // Only fetch if we are starting the survey or if we need to preload data
    // For now, we fetch when activeSurveyId changes, but we don't block UI unless we are entering SURVEY mode
    SurveyService.getSurveyById(activeSurveyId)
      .then((data) => {
        if (data) {
          setCurrentSurvey(data);
        }
      });
  }, [activeSurveyId]);

  const handleStartSurvey = (surveyId?: string) => {
    if (!user) {
      setLoginModalConfig({});
      setShowLoginModal(true);
      return;
    }

    setIsLoading(true);
    const surveyIdToStart = surveyId || activeSurveyId;

    // If starting a DIFFERENT survey on the same profile, update the profile's primary survey ID
    if (activeProfileId && surveyIdToStart) {
      const profile = profiles.find(p => p.id === activeProfileId);
      if (profile && profile.surveyId !== surveyIdToStart) {
        ProfileService.updateProfileSurveyId(activeProfileId, surveyIdToStart);
        setProfiles(ProfileService.getProfiles());
      }
    }

    SurveyService.getSurveyById(surveyIdToStart)
      .then((data) => {
        if (data) {
          setCurrentSurvey(data);
          navigate(`/survey/${surveyIdToStart}`);
        }
      })
      .finally(() => setIsLoading(false));
  };

  const fileInputRef = useRef<HTMLInputElement>(null);

  // Handle Theme Logic
  useEffect(() => {
    if (theme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [theme]);

  const toggleTheme = () => {
    const newTheme = theme === 'light' ? 'dark' : 'light';
    setTheme(newTheme);
    localStorage.setItem('neuroprofile_theme', newTheme);
  };

  const handleLogout = () => {
    localStorage.removeItem('auth_token');
    localStorage.removeItem('telegram_auth');
    localStorage.removeItem('neuroprofile_active_profile_id');
    localStorage.removeItem('neuroprofile_profiles');
    localStorage.removeItem('neuroprofile_user_id');
    localStorage.removeItem('aphantasia_consent_accepted');
    setUser(null);
    window.location.reload(); // Hard reload to clear all states and re-trigger initial modal
  };

  // Load answers from active profile for current survey
  useEffect(() => {
    if (activeProfileId) {
      const profile = profiles.find(p => p.id === activeProfileId);
      if (profile) {
        setAnswers(profile.answers[activeSurveyId] || {});
        localStorage.setItem('neuroprofile_active_profile_id', activeProfileId);
      }
    }
  }, [activeProfileId, activeSurveyId]);

  useEffect(() => {
    // Save state whenever it changes
    if (activeProfileId && Object.keys(answers).length > 0) {
      ProfileService.updateProfile(activeProfileId, activeSurveyId, answers, undefined, tone);
    }
  }, [answers, activeProfileId, activeSurveyId, tone]);

  useEffect(() => {
    // Warn on exit if in survey
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      if (appState === AppState.SURVEY && Object.keys(answers).length > 0) {
        e.preventDefault();
      }
    };

    globalThis.addEventListener('beforeunload', handleBeforeUnload);
    return () => globalThis.removeEventListener('beforeunload', handleBeforeUnload);
  }, [appState, answers]);


  // Derive Localized Data
  const localizedCategories: LocalizedCategoryData[] = useMemo(() => {
    if (!currentSurvey) return [];

    const localizeQuestion = (q: any) => ({
      id: q.id,
      category: q.category,
      type: q.type,
      text: q.text[language] || q.text['en'],
      placeholder: q.placeholder ? (q.placeholder[language] || q.placeholder['en']) : undefined,
      subCategory: q.subCategory ? (q.subCategory[language] || q.subCategory['en']) : undefined,
      hint: q.hint ? (q.hint[language] || q.hint['en']) : undefined,
      options: q.options?.map((opt: any) => ({
        value: opt.value,
        label: opt.label[language] || opt.label['en']
      }))
    });

    const localizeCategory = (cat: any) => ({
      id: cat.id,
      title: cat.title[language] || cat.title['en'],
      description: cat.description[language] || cat.description['en'],
      questions: cat.questions.map(localizeQuestion)
    });

    return currentSurvey.categories.map(localizeCategory);
  }, [language, currentSurvey]);

  const localizedScaleConfig: LocalizedScaleConfig | undefined = useMemo(() => {
    if (!currentSurvey || !currentSurvey.scaleConfig) return undefined;

    const labels: Record<number, string> = {};
    Object.entries(currentSurvey.scaleConfig.labels).forEach(([key, val]) => {
      labels[Number(key)] = val[language] || (val as any)['en'];
    });

    return {
      min: currentSurvey.scaleConfig.min,
      max: currentSurvey.scaleConfig.max,
      labels
    };
  }, [language, currentSurvey]);

  // Use memo to optimize translation object creation with fallback to English
  const ui = useMemo(() => {
    const base = UI_TRANSLATIONS['en'] || {};
    const current = UI_TRANSLATIONS[language] || {};
    return { ...base, ...current } as UIStrings;
  }, [language]);
  const activeCategory = localizedCategories[currentCategoryIndex];

  // Progress Calculation
  const activeProfile = useMemo(() => profiles.find(p => p.id === activeProfileId), [profiles, activeProfileId]);

  const isQuestionAnswered = (q: any, ans: Answer | undefined) => {
    if (!ans) return false;
    if (q.type === QuestionType.SCALE) return typeof ans.value === 'number';
    if (q.type === QuestionType.CHOICE) return typeof ans.value === 'string' && ans.value !== '';
    if (q.type === QuestionType.TEXT) return typeof ans.note === 'string' && ans.note.trim() !== '';
    if (q.type === QuestionType.DRAWING) return typeof ans.value === 'string' && ans.value.startsWith('data:image/');
    return false;
  };

  const surveyProgress = useMemo(() => {
    const progress: Record<string, { answered: number; total: number; percent: number }> = {};
    if (!activeProfile) return progress;

    AVAILABLE_SURVEYS.forEach(survey => {
      const questions = survey.categories.flatMap(c => c.questions);
      const total = questions.length;
      
      // Merge answers from self and parent (if any) to show unified progress
      let surveyAnswers = { ...(activeProfile.answers[survey.id] || {}) };
      if (survey.parentId && activeProfile.answers[survey.parentId]) {
        surveyAnswers = { ...activeProfile.answers[survey.parentId], ...surveyAnswers };
      }

      const answered = questions.filter(q => isQuestionAnswered(q, surveyAnswers[q.id])).length;
      progress[survey.id] = {
        answered,
        total,
        percent: total > 0 ? Math.round((answered / total) * 100) : 0
      };
    });

    return progress;
  }, [activeProfile, profiles]);

  const currentSurveyQuestions = useMemo(() => currentSurvey ? currentSurvey.categories.flatMap(c => c.questions) : [], [currentSurvey]);

  const totalQuestions = currentSurveyQuestions.length;
  const answeredCountInCurrentSurvey = useMemo(() => {
    return currentSurveyQuestions.filter(q => isQuestionAnswered(q, answers[q.id])).length;
  }, [currentSurveyQuestions, answers]);

  const progressPercent = totalQuestions > 0 ? Math.round((answeredCountInCurrentSurvey / totalQuestions) * 100) : 0;

  const handleAnswerChange = (questionId: string, value: string | number | null, note: string) => {
    setAnswers((prev) => {
      const newAnswers = {
        ...prev,
        [questionId]: { questionId, value, note },
      };

      // Update profile immediately
      if (activeProfileId) {
        ProfileService.updateProfile(activeProfileId, activeSurveyId, newAnswers, undefined, tone);
        setProfiles(ProfileService.getProfiles());
      }

      return newAnswers;
    });
  };

  const handleCreateProfile = (name: string) => {
    const newProfile = ProfileService.createProfile(name, activeSurveyId);
    setProfiles(ProfileService.getProfiles());
    setActiveProfileId(newProfile.id);
  };

  const handleDeleteProfile = (id: string) => {
    ProfileService.deleteProfile(id);
    const updatedProfiles = ProfileService.getProfiles();
    setProfiles(updatedProfiles);
    if (activeProfileId === id) {
      setActiveProfileId(updatedProfiles.length > 0 ? updatedProfiles[0].id : null);
    }
  };

  const handleSelectProfile = (id: string) => {
    setActiveProfileId(id);
    const profile = profiles.find(p => p.id === id);
    if (profile?.tone) {
      setTone(profile.tone);
    }
  };

  const handleRenameProfile = (id: string, newName: string) => {
    ProfileService.renameProfile(id, newName);
    setProfiles(ProfileService.getProfiles());
  };

  const handleRetake = (profileId?: string) => {
    const targetProfile = profileId ? profiles.find(p => p.id === profileId) : activeProfile;
    if (targetProfile) {
      const baseName = targetProfile.name.split(' (Retake')[0];
      const retakes = profiles.filter(p => p.name.startsWith(baseName)).length;
      const newName = `${baseName} (Retake ${retakes})`;
      const newProfile = ProfileService.createProfile(newName, targetProfile.surveyId || activeSurveyId);
      setProfiles(ProfileService.getProfiles());
      setActiveProfileId(newProfile.id);
      setActiveSurveyId(targetProfile.surveyId || activeSurveyId);
      navigate('/');
    }
  };

  const handleNavigate = (state: AppState) => {
    switch (state) {
      case AppState.INTRO: navigate('/'); break;
      case AppState.RESULTS: navigate('/results'); break;
      case AppState.RECOMMENDATIONS: navigate('/recommendations'); break;
      case AppState.DASHBOARD_RESULTS: navigate('/results'); break;
      case AppState.USERS: navigate('/users'); break;
      case AppState.SURVEY: navigate(`/survey/${activeSurveyId}`); break;
    }
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const nextCategory = () => {
    // Require auth before moving to the second part (Category 1 -> Category 2)
    if (currentCategoryIndex === 0 && !user) {
      setLoginModalConfig({
        title: ui.loginRequired,
        description: ui.loginToContinue
      });
      setShowLoginModal(true);
      return;
    }

    window.scrollTo({ top: 0, behavior: 'smooth' });
    if (currentCategoryIndex < localizedCategories.length - 1) {
      setCurrentCategoryIndex((prev) => prev + 1);
    } else {
      setShowFinishConfirmation(true);
    }
  };

  const finalizeFinish = () => {
    setShowFinishConfirmation(false);
    if (activeProfileId) {
      ProfileService.updateProfile(activeProfileId, activeSurveyId, answers, undefined, tone);
      setProfiles(ProfileService.getProfiles());
      navigate(`/results/${activeProfileId}`);
    } else {
      navigate('/results');
    }
  };

  const handleApplyImport = (profileId: string | null, loadedAnswers: Record<string, Answer>) => {
    let targetId = profileId;

    if (!profileId) {
      // Create new profile
      const newProfile = ProfileService.createProfile(ui.importedProfile, activeSurveyId);
      targetId = newProfile.id;
    }

    if (targetId) {
      ProfileService.updateProfile(targetId, activeSurveyId, loadedAnswers);
      setProfiles(ProfileService.getProfiles());
      if (targetId === activeProfileId) {
        setAnswers(loadedAnswers);
      } else {
        setActiveProfileId(targetId);
        setAnswers(loadedAnswers);
      }
    }

    setImportingAnswers(null);
    setAppState(AppState.SURVEY);
    setCurrentCategoryIndex(0);
  };

  const prevCategory = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
    if (currentCategoryIndex > 0) {
      setCurrentCategoryIndex((prev) => prev - 1);
    } else {
      setAppState(AppState.INTRO);
    }
  };

  const downloadProgress = () => {
    const profileName = activeProfile?.name || 'anonymous';
    const typeLabel = ProfileService.getProfileTypeLabel(activeProfile?.type, language) || 'unknown';
    const filename = `${profileName}_${typeLabel}_${activeSurveyId}_${new Date().toISOString().slice(0, 10)}.json`;

    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(answers, null, 2));
    const downloadAnchorNode = document.createElement('a');
    downloadAnchorNode.setAttribute("href", dataStr);
    downloadAnchorNode.setAttribute("download", filename);
    document.body.appendChild(downloadAnchorNode);
    downloadAnchorNode.click();
    downloadAnchorNode.remove();
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
        const content = event.target?.result as string;
        if (!content) return;

        let loadedAnswers = null;

        // Attempt to parse based on extension or content
        const isToon = file.name.endsWith('.toon');

        try {
          if (isToon) {
            loadedAnswers = decode(content);
          } else {
            // Try JSON
            const parsed = JSON.parse(content);
            // If the user uploaded a backend JSON export, extraction the answers part
            if (parsed && typeof parsed === 'object' && parsed.answers && typeof parsed.answers === 'object') {
              loadedAnswers = parsed.answers;
            } else {
              loadedAnswers = parsed;
            }
          }

          if (loadedAnswers && typeof loadedAnswers === 'object') {
            setImportingAnswers(loadedAnswers);
            // Clear input value to allow re-uploading the same file if needed
            if (fileInputRef.current) {
              fileInputRef.current.value = '';
            }
          }
        } catch (error) {
          console.error("Error parsing file", error);
          // Fallback: if JSON parse failed, maybe it was a TOON file named incorrectly or vice versa
          try {
            if (!isToon) {
              loadedAnswers = decode(content);
              if (loadedAnswers) {
                setImportingAnswers(loadedAnswers);
                return;
              }
            }
          } catch (e) {
            alert("Error reading file");
          }

        }
      };
      reader.readAsText(file);
    }
  };

  const triggerFileUpload = () => {
    fileInputRef.current?.click();
  };

  const handleViewAdminResult = (result: any) => {
    // result here is either the full object or we just need the userId and test_type
    const userId = result.user_id;
    const testType = result.test_type;
    
    if (userId && testType) {
        navigate(`/results/admin?userId=${userId}&surveyId=${testType}`);
    }
  };

  return (
    <div className="min-h-screen bg-brand-paper text-brand-graphite pb-20 font-sans transition-colors duration-300">
      <Header
        appState={appState}
        ui={ui}
        language={language}
        theme={theme}
        progressPercent={progressPercent}
        activeProfileName={activeProfile?.name}
        user={user}
        onSetLanguage={setLanguage}
        onToggleTheme={toggleTheme}
        onDownloadProgress={downloadProgress}
        onNavigate={handleNavigate}
        onLogout={handleLogout}
        isAdmin={isAdmin}
      />

      {/* Landing page routes render full-width, without max-w container */}
      <Routes>
        <Route path="/" element={
          !user ? (
            <LandingPage ui={ui} onStartSurvey={() => handleStartSurvey()} />
          ) : null
        } />
        <Route path="/landing" element={
          <LandingPage ui={ui} onStartSurvey={() => handleStartSurvey()} />
        } />
        <Route path="*" element={null} />
      </Routes>

      {/* All other routes get the standard padded container */}
      <main className="max-w-6xl mx-auto p-4 md:p-8 transition-all duration-500">
        <Routes>
          <Route path="/" element={
            user ? (
              <>
                {isAdmin && (
                  <ProfileManager
                    profiles={profiles}
                    activeProfileId={activeProfileId}
                    onSelect={handleSelectProfile}
                    onCreate={handleCreateProfile}
                    onDelete={handleDeleteProfile}
                    onRename={handleRenameProfile}
                    ui={ui}
                    lang={language}
                  />
                )}
                <Intro
                  ui={ui}
                  language={language}
                  activeSurveyId={activeSurveyId}
                  onSetActiveSurveyId={setActiveSurveyId}
                  onStartSurvey={handleStartSurvey}
                  onTriggerFileUpload={triggerFileUpload}
                  fileInputRef={fileInputRef}
                  onFileUpload={handleFileUpload}
                  isLoading={isLoading}
                  surveyProgress={surveyProgress}
                  hasExistingResults={hasExistingResults}
                  backendRecommendations={backendRecommendations}
                  onShowResults={(sid) => navigate(`/results/${activeProfileId}${sid ? `?surveyId=${sid}` : ''}`)}
                />
              </>
            ) : null
          } />

           <Route path="/results" element={
            <ProtectedRoute user={user}>
              <DashboardResults
                profiles={profiles}
                onViewResult={(id, sid) => {
                  if (id === 'ADMIN_OBJECT') {
                    handleViewAdminResult(sid);
                  } else {
                    navigate(`/results/${id}${sid ? `?surveyId=${sid}` : ''}`);
                  }
                }}
                ui={ui}
                language={language}
                isAdmin={isAdmin}
                adminResults={adminResults}
                onSetAdminResults={setAdminResults}
              />
            </ProtectedRoute>
          } />

          <Route path="/results/:profileId" element={
            <ResultsWrapper
              profiles={profiles}
              onReset={(id) => handleRetake(id)}
              onGoHome={() => navigate('/')}
              ui={ui}
              lang={language}
              user={user}
              activeSurveyId={activeSurveyId}
              setActiveProfileId={setActiveProfileId}
              backendRecommendations={backendRecommendations}
              adminResults={adminResults}
            />
          } />

          <Route path="/history" element={<Navigate to="/results" replace />} />
          <Route path="/dashboard" element={<Navigate to="/results" replace />} />

          <Route path="/recommendations" element={
            <ProtectedRoute user={user}>
              <Recommendations
                ui={ui}
                isLocked={!profiles.some(p => Object.keys(p.answers).length > 0)}
                user={user}
              />
            </ProtectedRoute>
          } />

          <Route path="/survey/:surveyId" element={
            <Survey
              ui={ui}
              currentCategoryIndex={currentCategoryIndex}
              totalCategories={localizedCategories.length}
              activeCategory={activeCategory}
              answers={answers}
              onAnswerChange={handleAnswerChange}
              onPrevCategory={prevCategory}
              onNextCategory={nextCategory}
              isLoading={isLoading}
              scaleConfig={localizedScaleConfig}
              isQuestionAnswered={isQuestionAnswered}
              showUnansweredIndicators={true}
              totalQuestions={totalQuestions}
              answeredCount={answeredCountInCurrentSurvey}
            />
          } />

          <Route path="/users" element={
            <ProtectedRoute user={user}>
              {isAdmin ? (
                <AdminDashboard
                  ui={ui}
                  lang={language}
                  onViewResult={handleViewAdminResult}
                  results={adminResults}
                  onSetResults={setAdminResults}
                />
              ) : <Navigate to="/" replace />}
            </ProtectedRoute>
          } />

          <Route path="/privacy" element={
            <PrivacyPolicy ui={ui} language={language} />
          } />

          <Route path="/about" element={
            <AboutPage ui={ui} onStartSurvey={() => handleStartSurvey()} />
          } />

          <Route path="/faq" element={
            <FaqPage ui={ui} language={language} />
          } />

          <Route path="/terms" element={
            <TermsPage ui={ui} />
          } />

          <Route path="/how-it-works" element={
            <HowItWorksPage ui={ui} language={language} onStartSurvey={() => handleStartSurvey()} />
          } />

          <Route path="/news" element={
            <NewsPage
              ui={ui}
              language={language}
              onStartSurvey={() => handleStartSurvey()}
            />
          } />

          <Route path="*" element={<Navigate to="/" replace />} />
        </Routes>
      </main>

      <FinishConfirmationModal
        isOpen={showFinishConfirmation}
        onClose={() => setShowFinishConfirmation(false)}
        onConfirm={finalizeFinish}
        ui={ui}
        language={language}
        onLanguageChange={setLanguage}
        tone={tone}
        onToneChange={(t) => {
          setTone(t);
          localStorage.setItem('neuroprofile_tone', t);
        }}
      />
      {importingAnswers && (
        <ImportManager
          profiles={profiles}
          newAnswers={importingAnswers}
          onImport={handleApplyImport}
          onCancel={() => setImportingAnswers(null)}
          ui={ui}
          lang={language}
        />
      )}

      <LoginModal
        isOpen={showLoginModal}
        onClose={() => setShowLoginModal(false)}
        ui={ui}
        title={loginModalConfig.title}
        description={loginModalConfig.description}
      />
    </div>
  );
};


const ResultsWrapper: React.FC<any> = ({ 
  profiles, 
  onReset, 
  ui, 
  lang, 
  user, 
  activeSurveyId, 
  setActiveProfileId, 
  backendRecommendations, 
  adminResults = [] 
}) => {
  const { profileId } = useParams();
  const [searchParams] = useSearchParams();
  const surveyIdFromQuery = searchParams.get('surveyId');
  const userIdFromQuery = searchParams.get('userId');
  const navigate = useNavigate();

  const [adminProfile, setAdminProfile] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  const profile = useMemo(() => {
    if (profileId === 'admin') return adminProfile;
    if (profileId) {
      return profiles.find((p: any) => p.id === profileId);
    }
    const activeId = localStorage.getItem('neuroprofile_active_profile_id');
    return profiles.find((p: any) => p.id === activeId);
  }, [profileId, profiles, adminProfile]);

  useEffect(() => {
    if (userIdFromQuery && profileId === 'admin') {
      // 1. Try to find in adminResults first
      const cached = adminResults.find((r: any) => r.user_id === userIdFromQuery && (r.test_type === surveyIdFromQuery || !surveyIdFromQuery));
      if (cached) {
         setAdminProfile({
            id: 'admin',
            name: `${cached.first_name} ${cached.last_name || ''}`,
            targetUser: {
              first_name: cached.first_name,
              last_name: cached.last_name,
              photo_url: cached.photo_url,
              username: cached.username
            },
            answers: cached.answers,
            surveyId: surveyIdFromQuery || cached.test_type,
            type: cached.scores?.Visual ? ProfileService.getProfileType(cached.scores.Visual) : undefined,
            recommendations: cached.gemini_recommendations,
            badges: cached.badges
         });
         setLoading(false);
         return;
      }

      // 2. Fallback to fetch
      setAdminProfile(null);
      setLoading(true);
      fetch(`${import.meta.env.VITE_API_URL || 'http://localhost:8000'}/api/results?user_id=${user?.id}&hash=${user?.hash}&target_user_id=${userIdFromQuery}`)
        .then(res => res.json())
        .then(data => {
          if (Array.isArray(data) && data.length > 0) {
            const result = data[0];
            setAdminProfile({
              id: 'admin',
              name: `${result.first_name} ${result.last_name || ''}`,
              targetUser: {
                first_name: result.first_name,
                last_name: result.last_name,
                photo_url: result.photo_url,
                username: result.username
              },
              answers: result.answers,
              surveyId: surveyIdFromQuery || result.test_type,
              type: result.scores?.Visual ? ProfileService.getProfileType(result.scores.Visual) : undefined,
              recommendations: result.gemini_recommendations,
              badges: result.badges
            });
          }
        })
        .finally(() => setLoading(false));
    }
  }, [userIdFromQuery, profileId, user?.id, user?.hash, adminResults, surveyIdFromQuery]);

  useEffect(() => {
    // If it's a local profile, we can stop loading immediately
    if (profile && profileId !== 'admin') {
      setLoading(false);
    }
  }, [profile, profileId]);

  const [publicProfile, setPublicProfile] = useState<any>(null);
  const [errorStatus, setErrorStatus] = useState<number | null>(null);

  useEffect(() => {
    // Only fetch public profile if we don't have a local profile AND it's not an admin view
    if (!profile && profileId && profileId !== 'admin' && !publicProfile && !errorStatus) {
      setLoading(true);
      fetch(`${import.meta.env.VITE_API_URL || 'http://localhost:8000'}/results/${profileId}`)
        .then(async res => {
          if (res.ok) return res.json();
          setErrorStatus(res.status);
          return null;
        })
        .then(data => {
          if (data) {
            setPublicProfile({
              id: data.user_id,
              isPublicView: true,
              public_nickname: data.public_nickname,
              name: data.public_nickname || 'Anonymous',
              answers: { [data.test_type]: data.answers || {} },
              surveyId: data.test_type,
              scores: data.scores,
              recommendations: data.gemini_recommendations,
              badges: data.badges
            });
          }
        })
        .catch(() => setErrorStatus(500))
        .finally(() => setLoading(false));
    }
  }, [profileId, profile, publicProfile, errorStatus]);

  const activeProfile = useMemo(() => profile || publicProfile, [profile, publicProfile]);

  if (loading) {
    return (
      <div className="min-h-[60vh] flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-brand-ink"></div>
      </div>
    );
  }

  if (profileId === 'admin' && !adminProfile && !loading) {
    return (
       <div className="min-h-[60vh] flex flex-col items-center justify-center text-center p-8">
         <ShieldAlert className="w-12 h-12 text-brand-clay mb-4" />
         <h2 className="text-2xl font-serif font-bold text-brand-graphite mb-2">{ui.noRecordsFound}</h2>
         <button onClick={() => navigate('/')} className="btn-primary px-8 mt-4">{ui.goHome}</button>
       </div>
    );
  }

  if (errorStatus === 403) {
    return (
      <div className="min-h-[60vh] flex flex-col items-center justify-center text-center p-8">
        <ShieldAlert className="w-12 h-12 text-brand-clay mb-4" />
        <h2 className="text-2xl font-serif font-bold text-brand-graphite mb-2">This profile is private.</h2>
        <button onClick={() => navigate('/')} className="btn-primary px-8 mt-4">{ui.goHome}</button>
      </div>
    );
  }

  if (!activeProfile && !loading) {
    return <Navigate to="/" replace />;
  }

  return (
    <Results
      key={`${activeProfile.id}_${userIdFromQuery || ''}_${surveyIdFromQuery || ''}`}
      answers={activeProfile.answers}
      onReset={() => onReset(activeProfile.id)}
      onGoHome={() => navigate('/')}
      ui={ui}
      lang={lang}
      filenamePrefix={userIdFromQuery ? `${activeProfile.name || 'user'}_${userIdFromQuery}` : `${activeProfile.name || 'anonymous'}_results`}
      user={user}
      targetUser={activeProfile.targetUser}
      surveyId={surveyIdFromQuery || activeProfile.surveyId || activeSurveyId}
      initialRecommendations={activeProfile.recommendations || (userIdFromQuery ? {} : backendRecommendations)}
      badges={activeProfile.badges}
      isPublicView={activeProfile.isPublicView}
      publicNickname={activeProfile.public_nickname}
    />
  );
}

export default App;
