FROM node:22-slim AS base
WORKDIR /app
COPY package*.json ./
RUN npm install --include=optional
COPY . .

FROM base AS build
ARG VITE_API_URL
ARG VITE_TELEGRAM_BOT_NAME
ARG VITE_TELEGRAM_CLIENT_ID
ARG VITE_ADMIN_TELEGRAM_IDS
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_TELEGRAM_BOT_NAME=$VITE_TELEGRAM_BOT_NAME
ENV VITE_TELEGRAM_CLIENT_ID=$VITE_TELEGRAM_CLIENT_ID
ENV VITE_ADMIN_TELEGRAM_IDS=$VITE_ADMIN_TELEGRAM_IDS
RUN npm run build

FROM nginx:alpine AS prod
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
