name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
          script: |
            set -e
            cd ${{ secrets.DEPLOY_PATH }}
            echo "Current user: $(whoami)"
            
            # Use sudo if necessary to fix permissions or pull updates
            sudo git fetch origin
            sudo git pull origin main
            
            # Build and up using sudo
            sudo make prod-build
            sudo make prod-up
